[[services]]
name = "app1"
cmd = "./examples/main1/main1"
args = ["-f", "testfile"]
disable = false

[[services]]
name = "app2"
cmd = "./examples/main2/main2"

[[services]]
name = "app-not-exists-3"
cmd = "./examples/main2/main3"
